configure detects pthreads, CERR and MARK macros removed

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -40,8 +40,8 @@ add_lib() {
   fi
 }
 
+# check for includes
 search_includes() {
-  # check for includes
   inc=""
   for dbn in "" ${subdirs}; do
     for dir in ${DIRS};  do
@@ -55,8 +55,8 @@ search_includes() {
   return 1
 }
 
+# check for libs
 search_lib() {
-  # check for includes
   inc=""
   for dbn in $@; do
     for dir in ${DIRS};  do
@@ -71,20 +71,30 @@ search_lib() {
 }
  
 
-
+######################## DB
 subdirs="/db /db3 /db4"
 search_includes db_cxx.h || err "The Berkeley DB header files were not found"
+search_lib db4_cxx db3_cxx db_cxx-4 db_cxx-3 db_cxx || err "The Berkeley DB library was not found. Try installing db-dev" 
+## The fun of NPTL... (Thx Enrico Scholz)
+echo 'int main() {}' >conftest.c
+if g++ $LIBS $LDIRS $CF $CFLAGS conftest.c -o conftest &>/dev/null ; then
+	:
+else
+	search_lib pthread || err "Lib pthread needed for db_cxx and not found"
+fi
+#rm -f conftest.c conftest
 
+####################### OpenSSL
 subdirs=""
 search_includes openssl/opensslv.h || err "The OpenSSL library headerfiles were not found."
+search_lib crypto || err "The OpenSSL library was not found."
 
+######################### QT
 subdirs="/qt"
 search_includes qobject.h || err "The QT Library headerfiles were not found. Set QTDIR appropriately."
-
-search_lib c_r || true
-search_lib db4_cxx db3_cxx db_cxx-4 db_cxx-3 db_cxx || err "The Berkeley DB library was not found. Try installing db-dev" 
-search_lib crypto || err "The OpenSSL library was not found."
 search_lib qt qt-mt || err "The QT library was not found. Try installing qt-dev" 
+search_lib c_r || true
+
 
 if test -x $QTDIR/bin/moc; then
   MOC="$QTDIR/bin/moc"
@@ -95,7 +105,7 @@ if test -x $QTDIR/bin/uic; then
 fi
 
 cat >Local.mak <<EOF
-CPPFLAGS="$CF" 
+CPPFLAGS=$CF
 CFLAGS=${CFLAGS:--Wall}
 
 LDFLAGS=$LDIRS
